---
title: "Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
p8105.datasets::instacart
```


Column {data-width=450}
-----------------------------------------------------------------------

### Number of People Purchasing Alcohol per Hour  

```{r}
a = list(title = "Hour of the Day")
b = list(title = "Number of Customers")

instacart %>% 
    janitor::clean_names() %>%
    select(department, order_hour_of_day, order_id) %>%
    filter(department == "alcohol") %>%
    group_by(order_hour_of_day) %>%
    count(n = n_distinct(order_id)) %>%
    plot_ly(x = ~order_hour_of_day, y = ~n, type = "scatter", mode = "marker", 
            alpha = 0.5) %>%
            layout(xaxis = a, yaxis = b)
```

### Number of People Purchasing Alcohol per Day of the Week 

```{r}
c = list(title = "Day of the Week")
d = list(title = "Number of Customers")

instacart %>% 
    janitor::clean_names() %>%
    select(department, order_dow, order_id) %>%
    filter(department == "alcohol") %>%
    mutate(order_dow = as.character(order_dow)) %>%
    mutate(order_dow = recode(order_dow, `0` = "Sunday", `1` = "Monday", `2` = "Tuesday", `3` = "Wednesday", `4` = "Thursday", `5` = "Friday", `6` = "Saturday")) %>%
    group_by(order_dow) %>%
    count(n = n_distinct(order_id)) %>%
    plot_ly(x = ~order_dow, y = ~n, type = "bar", 
            alpha = 0.5) %>%
            layout(xaxis = c, yaxis = d) 
```


Column {data-width=550}
-----------------------------------------------------------------------

### Number of Days Since Last Order by Department with Food Items  

```{r}
x = list(title = "Department")
y = list(title = "Number of Days Since Prior Order")
set.seed(1)
perish_np = instacart %>% 
    janitor::clean_names() %>%
    filter(department == "produce" | department == "meat seafood" | department == "dairy eggs" | department == "international" | department == "pantry" | department == "snacks" | department == "canned goods" | department == "alcohol" | department == "bakery" | department == "babies" | department == "breakfast" |  department == "frozen" |  department == "bulk" | department == "dry goods pasta" | department == "beverages" |  department == "deli") %>%
    sample_n(500) %>%
    select(-add_to_cart_order, -eval_set, -aisle, -aisle_id, -department_id, -order_hour_of_day, -order_dow)
perish_np %>%
  mutate(department = fct_reorder(department, days_since_prior_order)) %>% 
  plot_ly(x = ~department, y = ~days_since_prior_order, type = "box", 
            alpha = 0.5) %>%
            layout(xaxis = x, yaxis = y)
```
